C4Context
  title Context Diagram for MSA-AgroTech
  System(sensor, "Датчик/видеокамера", "Снимает данные с ангара/загона/кормушки")
  System(agent, "Edge-устройство", "Видеоаналитика")
  System(partner_ai, "Партнёрская ИИ-модель", "Для обработки данных с камер/датчиков")
  System(central_server, "Центральный сервер", "Хранение и управление всеми данными на ферме")
  Person(employee, "Ответственный сотрудник", "Реагирует на все нештатные ситуации")
  Person(admin, "Администратор системы", "Настраивает метрики и управляет системой")
  System_Ext(ui_app, "Мобильное или веб-приложение", "Позволяет взаимодействовать с системой через API")

  Rel(admin, ui_app, "Управляет")
  Rel(ui_app, central_server, "Вызывает API")
  Rel(agent, employee, "Отправляет SMS с данными, где произошёл инцидент")
  Rel(sensor, agent, "Отправляет данные")
  Rel_D(partner_ai, agent, "Использует для расчётов")
  Rel(agent, central_server, "Отправляет данные")
